---
title: "exploration"
header-includes: |
  \makeatletter
  \def\verbatim@nolig@list{}
  \makeatother
  \usepackage{cancel}
  \usepackage[fontsize=9.5pt]{scrextend}
output:
  html_document:
    df_print: paged
  pdf_document:
    highlight: default
    latex_engine: xelatex
    number_sections: yes
classoption: landscape
monofont: Fira Code Retina
geometry: margin=0.5in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Hmisc)
library(tidyverse)
library(boot)
set.seed(42)
options(boot.parallel='multicore')
options(boot.ncpus=8)
```

# Data wrangling

```{r}
forms <- 1:7

results2tbl <- function(model_prefix, sents_prefix, n) {
  for (i in n) {
    # Bind all the result tsv's into one tbl, with a column for experiment;
    # Add columns from the data tsvs which were generated post-experiment
    # (in future, results output shouldn't need to have extra cols at all)
    input <- read.csv(paste(model_prefix, i, '.tsv', sep=''), sep='\t') %>%
      bind_cols(select(
        read.csv(paste(sents_prefix, i, '.tsv', sep=''), sep='\t'),
        connective.summ, subform.id  # Whether the connective is a summary or contrast type; subform id (specified in templates)
      )) %>%
      mutate(Experiment=i)
    if (i == 1) results <- tbl_df(input)
    else results <- bind_rows(results, input)
  }
  # Convert string T/F to boolean; rename 'correct' -> 'matches'
  results <- results %>%
    mutate(correct=(correct=="True")) %>%
    rename(matches=correct) %>%
    mutate(crossing=(crossing=="True")) %>%
    mutate(connective.summ=(connective.summ=="True")) %>%
    mutate(subform.id=factor(subform.id))
  # Capitalize
  names(results) <- Hmisc::capitalize(names(results))
  return(results)
}
```

```{r}
lm1b <- results2tbl('lm1b_', '../data/small_sents', forms) %>% mutate(Model='lm1b')
gpt2 <- results2tbl('gpt2_', '../data/sents', forms) %>% mutate(Model='gpt2')

# Just a taste...
print(sample_n(lm1b, 10))
print(sample_n(gpt2, 10))
```

```{r}
summ <- bind_rows(lm1b, gpt2) %>%
  group_by(Experiment, Subform.id, Connective.summ, Matches, Model) %>%
  summarize(avg=mean(Inference))

ggplot(summ %>% filter(Model=='lm1b'), aes(x=Experiment, y=avg, fill=interaction(Connective.summ, Matches, Subform.id))) +
  geom_bar(stat="identity", position="dodge") +
  # geom_boxplot(alpha=0, color='black', notch=F) +
  scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(lm1b) Errything")

ggplot(summ %>% filter(Model=='gpt2'), aes(x=Experiment, y=avg, fill=interaction(Connective.summ, Matches, Subform.id))) +
  geom_bar(stat="identity", position="dodge") +
  # geom_boxplot(alpha=0, color='black', notch=F) +
  scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(gpt2) Errything")
```

# Does NN know enough about SVO dependencies to be less surprised at summary than contrast? (MATCHING ONLY)

```{r}
avgs_summ <- bind_rows(lm1b, gpt2) %>%
  filter(Connective.summ==T) %>%
  group_by(Experiment, Subform.id, Matches, Model) %>%
  summarize(avg.summ=mean(Inference))

avgs_contr <- bind_rows(lm1b, gpt2) %>%
  filter(Connective.summ==F) %>%
  group_by(Experiment, Subform.id, Matches, Model) %>%
  summarize(avg.contr=mean(Inference))

# note that these two tbls rows correspond; sum(avgs_summ[,1:4]!=avgs_contr[,1:4]) = 0

avgs <- avgs_summ %>%
  bind_cols(avg.contr=avgs_contr$avg.contr) %>%
  mutate(avg.diff=(avg.summ - avg.contr)) %>%
  filter(Matches==T)  # MATCHING ONLY

ggplot(avgs %>% filter(Model=='lm1b'), aes(x=Experiment, y=avg.diff, fill=Subform.id)) +
  geom_bar(stat="identity", position="dodge") +
  # scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(lm1b) Summary - Contrast, Matching=T")

ggplot(avgs %>% filter(Model=='gpt2'), aes(x=Experiment, y=avg.diff, fill=Subform.id)) +
  geom_bar(stat="identity", position="dodge") +
  # scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(gpt2) Summary - Contrast, Matching=T")
```

# Does NN know enough about SVO dependencies to be less surprised at matching than mismatched? (SUMMARY ONLY)

```{r}
avgs_match <- bind_rows(lm1b, gpt2) %>%
  filter(Matches==T) %>%
  group_by(Experiment, Subform.id, Connective.summ, Model) %>%
  summarize(avg.match=mean(Inference))

avgs_mismatch <- bind_rows(lm1b, gpt2) %>%
  filter(Matches==F) %>%
  group_by(Experiment, Subform.id, Connective.summ, Model) %>%
  summarize(avg.mismatch=mean(Inference))

# note that these two tbls rows correspond; sum(avgs_summ[,1:4]!=avgs_contr[,1:4]) = 0

avgs <- avgs_match %>%
  bind_cols(avg.mismatch=avgs_mismatch$avg.mismatch) %>%
  mutate(avg.diff=(avg.match - avg.mismatch)) %>%
  filter(Connective.summ==T)

ggplot(avgs %>% filter(Model=='lm1b'), aes(x=Experiment, y=avg.diff, fill=Subform.id)) +
  geom_bar(stat="identity", position="dodge") +
  # scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(lm1b) Matching - Mismatched, Summary=T")

ggplot(avgs %>% filter(Model=='gpt2'), aes(x=Experiment, y=avg.diff, fill=Subform.id)) +
  geom_bar(stat="identity", position="dodge") +
  # scale_fill_grey(start = 0, end = .95) + theme_bw() +
  scale_x_continuous(breaks=forms) +
  ggtitle("(gpt2) Matching - Mismatched, Summary=T")
```